apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: wait-action
  title: wait-action
  description: template with a waiting task for a long running action
spec:
  owner: user:guest
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          default: some value
          ui:autofocus: true
          ui:options:
            rows: 5

  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    - id: someAsyncCall
      name: Some Async Call
      action: debug:log
      input:
        message: Some async call that return a tickedId (guid, for instance, that identifies a process)

    - id: waitWorkflow
      name: Wait Creation
      action: goc:waitWorkflow
      input:
        ticketId: '1' #${{ steps.someAsyncCall.output.ticketId }}
        delayMilliseconds: 1000
        maxCalls: 30
